CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "bonus_points" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "menu_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
"price" decimal NOT NULL CHECK (price >= 0),
  "available" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "promotions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
"discount_type" varchar NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  "discount_value" decimal NOT NULL,
  "usage_limit" integer,
  "used_count" integer NOT NULL DEFAULT 0,
  "expires_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "couriers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
"status" varchar NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'busy', 'offline')),
"created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "courier_id" integer,
  "promotion_id" integer,
  "status" varchar NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'preparing', 'ready', 'out_for_delivery', 'delivered', 'cancelled')),
  "total_price" decimal NOT NULL,
  "discount_amount" decimal NOT NULL DEFAULT 0,
  "final_price" decimal NOT NULL,
  "notes" text,
  "delivery_address" text,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "menu_item_id" integer NOT NULL,
  "quantity" integer NOT NULL CHECK (quantity > 0),
  "unit_price" decimal NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "order_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "status" varchar NOT NULL,
  "note" text,
  "changed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "bonus_transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "order_id" integer,
  "type" varchar NOT NULL CHECK (type IN ('earned', 'redeemed')),
  "points" integer NOT NULL,
  "reason" text,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

COMMENT ON COLUMN "promotions"."discount_type" IS 'percentage or fixed';

COMMENT ON COLUMN "couriers"."status" IS 'available, busy, offline';

COMMENT ON COLUMN "orders"."status" IS 'pending, confirmed, preparing, ready, out_for_delivery, delivered, cancelled';

COMMENT ON COLUMN "bonus_transactions"."type" IS 'earned or redeemed';

ALTER TABLE "menu_items" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("courier_id") REFERENCES "couriers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bonus_transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bonus_transactions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;
-- =============================================
-- Seed data
-- =============================================

INSERT INTO categories (name) VALUES
    ('Burgers'),
    ('Drinks'),
    ('Desserts'),
    ('Snacks')
ON CONFLICT DO NOTHING;