// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/menu_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/menu_repository.go -destination=internal/repository/mocks/menu_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
