// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/order_repository.go -destination=internal/repository/mocks/order_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "bar108/internal/db"
	repository "bar108/internal/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *MockOrderRepository) AssignCourier(ctx context.Context, orderID, courierID int32) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, orderID, courierID)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockOrderRepositoryMockRecorder) AssignCourier(ctx, orderID, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockOrderRepository)(nil).AssignCourier), ctx, orderID, courierID)
}

// CancelOrder mocks base method.
func (m *MockOrderRepository) CancelOrder(ctx context.Context, id int32) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, id)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderRepositoryMockRecorder) CancelOrder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderRepository)(nil).CancelOrder), ctx, id)
}

// GetAllCouriers mocks base method.
func (m *MockOrderRepository) GetAllCouriers(ctx context.Context) ([]db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockOrderRepositoryMockRecorder) GetAllCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockOrderRepository)(nil).GetAllCouriers), ctx)
}

// GetAllOrders mocks base method.
func (m *MockOrderRepository) GetAllOrders(ctx context.Context) ([]db.GetAllOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", ctx)
	ret0, _ := ret[0].([]db.GetAllOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrderRepositoryMockRecorder) GetAllOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetAllOrders), ctx)
}

// GetAvailableCouriers mocks base method.
func (m *MockOrderRepository) GetAvailableCouriers(ctx context.Context) ([]db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableCouriers", ctx)
	ret0, _ := ret[0].([]db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableCouriers indicates an expected call of GetAvailableCouriers.
func (mr *MockOrderRepositoryMockRecorder) GetAvailableCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableCouriers", reflect.TypeOf((*MockOrderRepository)(nil).GetAvailableCouriers), ctx)
}

// GetCourierByID mocks base method.
func (m *MockOrderRepository) GetCourierByID(ctx context.Context, id int32) (db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierByID", ctx, id)
	ret0, _ := ret[0].(db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierByID indicates an expected call of GetCourierByID.
func (mr *MockOrderRepositoryMockRecorder) GetCourierByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierByID", reflect.TypeOf((*MockOrderRepository)(nil).GetCourierByID), ctx, id)
}

// GetOrderByID mocks base method.
func (m *MockOrderRepository) GetOrderByID(ctx context.Context, id int32) (db.GetOrderByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(db.GetOrderByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderRepositoryMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderByID), ctx, id)
}

// GetOrderItems mocks base method.
func (m *MockOrderRepository) GetOrderItems(ctx context.Context, orderID int32) ([]db.GetOrderItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItems", ctx, orderID)
	ret0, _ := ret[0].([]db.GetOrderItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItems indicates an expected call of GetOrderItems.
func (mr *MockOrderRepositoryMockRecorder) GetOrderItems(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItems", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderItems), ctx, orderID)
}

// GetOrderStatusHistory mocks base method.
func (m *MockOrderRepository) GetOrderStatusHistory(ctx context.Context, orderID int32) ([]db.OrderStatusHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatusHistory", ctx, orderID)
	ret0, _ := ret[0].([]db.OrderStatusHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatusHistory indicates an expected call of GetOrderStatusHistory.
func (mr *MockOrderRepositoryMockRecorder) GetOrderStatusHistory(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatusHistory", reflect.TypeOf((*MockOrderRepository)(nil).GetOrderStatusHistory), ctx, orderID)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderRepository) GetOrdersByUserID(ctx context.Context, userID int32) ([]db.GetOrdersByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]db.GetOrdersByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderRepositoryMockRecorder) GetOrdersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrdersByUserID), ctx, userID)
}

// GetPendingOrders mocks base method.
func (m *MockOrderRepository) GetPendingOrders(ctx context.Context) ([]db.GetPendingOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOrders", ctx)
	ret0, _ := ret[0].([]db.GetPendingOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOrders indicates an expected call of GetPendingOrders.
func (mr *MockOrderRepositoryMockRecorder) GetPendingOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetPendingOrders), ctx)
}

// PlaceOrder mocks base method.
func (m *MockOrderRepository) PlaceOrder(ctx context.Context, input repository.PlaceOrderInput) (repository.PlaceOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceOrder", ctx, input)
	ret0, _ := ret[0].(repository.PlaceOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceOrder indicates an expected call of PlaceOrder.
func (mr *MockOrderRepositoryMockRecorder) PlaceOrder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceOrder", reflect.TypeOf((*MockOrderRepository)(nil).PlaceOrder), ctx, input)
}

// UpdateCourierStatus mocks base method.
func (m *MockOrderRepository) UpdateCourierStatus(ctx context.Context, id int32, status string) (db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourierStatus", ctx, id, status)
	ret0, _ := ret[0].(db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCourierStatus indicates an expected call of UpdateCourierStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateCourierStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourierStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateCourierStatus), ctx, id, status)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderRepository) UpdateOrderStatus(ctx context.Context, id int32, status string) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, id, status)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderRepositoryMockRecorder) UpdateOrderStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderRepository)(nil).UpdateOrderStatus), ctx, id, status)
}
