package repository

import (
	"bar108/internal/db"
	"context"
	"database/sql"
	"fmt"
	"strconv"
	"time"
)

// =============================================
// Input structs — what PlaceOrder needs
// These are NOT generated by SQLC because they
// represent our business logic, not a table
// =============================================

// OrderItemInput represents one item in an incoming order request.
// The customer sends menu_item_id + quantity — we look up the price ourselves.
type OrderItemInput struct {
	MenuItemID int32
	Quantity   int32
}

// PlaceOrderInput is everything needed to create a full order.
// Using a struct instead of many parameters makes the code
// readable and easy to extend later.
type PlaceOrderInput struct {
	UserID          int32
	Items           []OrderItemInput
	PromoCode       string // empty string means no promo
	DeliveryAddress string
	Notes           string
}

// PlaceOrderResult is everything we return after placing an order.
// The handler needs the full order + its items to build the response.
type PlaceOrderResult struct {
	Order      db.Order
	Items      []db.OrderItem
	TotalPrice string
	FinalPrice string
}

// =============================================
// Interface
// =============================================

type OrderRepository interface {
	// Transaction operation — places a full order atomically
	PlaceOrder(ctx context.Context, input PlaceOrderInput) (PlaceOrderResult, error)

	// Single query operations
	GetOrderByID(ctx context.Context, id int32) (db.GetOrderByIDRow, error)
	GetOrdersByUserID(ctx context.Context, userID int32) ([]db.GetOrdersByUserIDRow, error)
	GetAllOrders(ctx context.Context) ([]db.GetAllOrdersRow, error)
	GetPendingOrders(ctx context.Context) ([]db.GetPendingOrdersRow, error)
	GetOrderItems(ctx context.Context, orderID int32) ([]db.GetOrderItemsRow, error)
	GetOrderStatusHistory(ctx context.Context, orderID int32) ([]db.OrderStatusHistory, error)
	UpdateOrderStatus(ctx context.Context, id int32, status string) (db.Order, error)
	AssignCourier(ctx context.Context, orderID int32, courierID int32) (db.Order, error)
	CancelOrder(ctx context.Context, id int32) (db.Order, error)

	// Courier operations
	GetAllCouriers(ctx context.Context) ([]db.Courier, error)
	GetAvailableCouriers(ctx context.Context) ([]db.Courier, error)
	GetCourierByID(ctx context.Context, id int32) (db.Courier, error)
	UpdateCourierStatus(ctx context.Context, id int32, status string) (db.Courier, error)
}

// =============================================
// Concrete implementation
// =============================================

type orderRepository struct {
	db      *sql.DB     // the raw DB — needed to start transactions
	queries *db.Queries // SQLC queries — used for non-transactional operations
}

func NewOrderRepository(conn *sql.DB) OrderRepository {
	return &orderRepository{
		db:      conn,
		queries: db.New(conn),
	}
}

// =============================================
// PlaceOrder — THE most important function
// Everything inside runs in one transaction.
// =============================================

func (r *orderRepository) PlaceOrder(ctx context.Context, input PlaceOrderInput) (PlaceOrderResult, error) {
	// STEP 1 — Start the transaction
	// BeginTx takes a context (for cancellation/timeout) and options (nil = defaults)
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return PlaceOrderResult{}, fmt.Errorf("PlaceOrder begin tx: %w", err)
	}

	// STEP 2 — Defer rollback
	// This runs when the function returns.
	// If Commit() was called successfully, Rollback() does nothing.
	// If we returned early due to an error, Rollback() cleans everything up.
	defer func() {
		_ = tx.Rollback()
	}()

	// STEP 3 — Create a SQLC Queries bound to the transaction
	// All queries from here use qtx — they're all part of the same transaction
	qtx := r.queries.WithTx(tx)

	// STEP 4 — Look up each menu item and calculate the total price
	// We do this INSIDE the transaction so no items can be deleted
	// between our check and our insert
	var totalPrice float64
	var orderItems []db.CreateOrderItemParams

	for _, item := range input.Items {
		// Fetch the menu item to get its current price
		menuItem, err := qtx.GetMenuItemByID(ctx, item.MenuItemID)
		if err != nil {
			if err == sql.ErrNoRows {
				return PlaceOrderResult{}, fmt.Errorf("menu item %d not found", item.MenuItemID)
			}
			return PlaceOrderResult{}, fmt.Errorf("PlaceOrder get menu item: %w", err)
		}

		// Check the item is available
		if !menuItem.Available {
			return PlaceOrderResult{}, fmt.Errorf("menu item '%s' is not available", menuItem.Name)
		}

		// Parse price — SQLC returns price as string for NUMERIC type
		var price float64
		if _, err := fmt.Sscanf(menuItem.Price, "%f", &price); err != nil {
			return PlaceOrderResult{}, fmt.Errorf("PlaceOrder parse price: %w", err)
		}

		// Accumulate total
		totalPrice += price * float64(item.Quantity)

		// Prepare the order item for insertion
		orderItems = append(orderItems, db.CreateOrderItemParams{
			MenuItemID: item.MenuItemID,
			Quantity:   item.Quantity,
			UnitPrice:  menuItem.Price, // snapshot — locks in current price
		})
	}

	// STEP 5 — Apply promo code if provided
	var discountAmount float64
	var promotionID sql.NullInt32 // nullable — not every order has a promo

	if input.PromoCode != "" {
		promo, err := qtx.GetPromotionByCode(ctx, input.PromoCode)
		if err != nil {
			if err == sql.ErrNoRows {
				return PlaceOrderResult{}, fmt.Errorf("promo code '%s' not found", input.PromoCode)
			}
			return PlaceOrderResult{}, fmt.Errorf("PlaceOrder get promo: %w", err)
		}

		// Check promo hasn't expired
		if promo.ExpiresAt.Valid && promo.ExpiresAt.Time.Before(time.Now()) {
			return PlaceOrderResult{}, fmt.Errorf("promo code '%s' has expired", input.PromoCode)
		}

		// Check usage limit hasn't been reached
		if promo.UsageLimit.Valid && promo.UsedCount >= promo.UsageLimit.Int32 {
			return PlaceOrderResult{}, fmt.Errorf("promo code '%s' has reached its usage limit", input.PromoCode)
		}

		// Calculate discount
		promoValue, err := strconv.ParseFloat(promo.DiscountValue, 64)
		if err != nil {
			return PlaceOrderResult{}, fmt.Errorf("PlaceOrder invalid promo value: %w", err)
		}

		if promo.DiscountType == "percentage" {
			discountAmount = totalPrice * (promoValue / 100)
		} else { // fixed
			discountAmount = promoValue
			if discountAmount > totalPrice {
				discountAmount = totalPrice // can't discount more than the total
			}
		}

		promotionID = sql.NullInt32{Int32: promo.ID, Valid: true}

		// Increment usage count — inside the transaction so it rolls back if order fails
		if _, err := qtx.IncrementPromotionUsage(ctx, promo.ID); err != nil {
			return PlaceOrderResult{}, fmt.Errorf("PlaceOrder increment promo usage: %w", err)
		}
	}

	// STEP 6 — Calculate final price
	finalPrice := totalPrice - discountAmount

	// STEP 7 — Create the order row
	order, err := qtx.CreateOrder(ctx, db.CreateOrderParams{
		UserID:          input.UserID,
		PromotionID:     promotionID,
		Status:          "pending",
		TotalPrice:      fmt.Sprintf("%.2f", totalPrice),
		DiscountAmount:  fmt.Sprintf("%.2f", discountAmount),
		FinalPrice:      fmt.Sprintf("%.2f", finalPrice),
		Notes:           sql.NullString{String: input.Notes, Valid: input.Notes != ""},
		DeliveryAddress: sql.NullString{String: input.DeliveryAddress, Valid: input.DeliveryAddress != ""},
	})
	if err != nil {
		return PlaceOrderResult{}, fmt.Errorf("PlaceOrder create order: %w", err)
	}

	// STEP 8 — Create all order items
	var createdItems []db.OrderItem
	for _, item := range orderItems {
		item.OrderID = order.ID // now we have the order ID
		created, err := qtx.CreateOrderItem(ctx, item)
		if err != nil {
			return PlaceOrderResult{}, fmt.Errorf("PlaceOrder create order item: %w", err)
		}
		createdItems = append(createdItems, created)
	}

	// STEP 9 — Record first status in history
	// This is the starting point of the order timeline the customer will see
	_, err = qtx.CreateOrderStatusHistory(ctx, db.CreateOrderStatusHistoryParams{
		OrderID: order.ID,
		Status:  "pending",
		Note:    sql.NullString{String: "Order placed successfully", Valid: true},
	})
	if err != nil {
		return PlaceOrderResult{}, fmt.Errorf("PlaceOrder create status history: %w", err)
	}

	// STEP 10 — Commit the transaction
	// Only if ALL steps above succeeded
	if err := tx.Commit(); err != nil {
		return PlaceOrderResult{}, fmt.Errorf("PlaceOrder commit: %w", err)
	}

	return PlaceOrderResult{
		Order:      order,
		Items:      createdItems,
		TotalPrice: fmt.Sprintf("%.2f", totalPrice),
		FinalPrice: fmt.Sprintf("%.2f", finalPrice),
	}, nil
}

// =============================================
// Single query operations — straightforward,
// no transaction needed
// =============================================

func (r *orderRepository) GetOrderByID(ctx context.Context, id int32) (db.GetOrderByIDRow, error) {
	order, err := r.queries.GetOrderByID(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return db.GetOrderByIDRow{}, fmt.Errorf("order %d not found: %w", id, sql.ErrNoRows)
		}
		return db.GetOrderByIDRow{}, fmt.Errorf("GetOrderByID: %w", err)
	}
	return order, nil
}

func (r *orderRepository) GetOrdersByUserID(ctx context.Context, userID int32) ([]db.GetOrdersByUserIDRow, error) {
	orders, err := r.queries.GetOrdersByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("GetOrdersByUserID: %w", err)
	}
	return orders, nil
}

func (r *orderRepository) GetAllOrders(ctx context.Context) ([]db.GetAllOrdersRow, error) {
	orders, err := r.queries.GetAllOrders(ctx)
	if err != nil {
		return nil, fmt.Errorf("GetAllOrders: %w", err)
	}
	return orders, nil
}

func (r *orderRepository) GetPendingOrders(ctx context.Context) ([]db.GetPendingOrdersRow, error) {
	orders, err := r.queries.GetPendingOrders(ctx)
	if err != nil {
		return nil, fmt.Errorf("GetPendingOrders: %w", err)
	}
	return orders, nil
}

func (r *orderRepository) GetOrderItems(ctx context.Context, orderID int32) ([]db.GetOrderItemsRow, error) {
	items, err := r.queries.GetOrderItems(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("GetOrderItems: %w", err)
	}
	return items, nil
}

func (r *orderRepository) GetOrderStatusHistory(ctx context.Context, orderID int32) ([]db.OrderStatusHistory, error) {
	history, err := r.queries.GetOrderStatusHistory(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("GetOrderStatusHistory: %w", err)
	}
	return history, nil
}

func (r *orderRepository) UpdateOrderStatus(ctx context.Context, id int32, status string) (db.Order, error) {
	order, err := r.queries.UpdateOrderStatus(ctx, db.UpdateOrderStatusParams{
		ID:     id,
		Status: status,
	})
	if err != nil {
		if err == sql.ErrNoRows {
			return db.Order{}, fmt.Errorf("order %d not found: %w", id, sql.ErrNoRows)
		}
		return db.Order{}, fmt.Errorf("UpdateOrderStatus: %w", err)
	}
	return order, nil
}

func (r *orderRepository) AssignCourier(ctx context.Context, orderID int32, courierID int32) (db.Order, error) {
	order, err := r.queries.AssignCourier(ctx, db.AssignCourierParams{
		ID:        orderID,
		CourierID: sql.NullInt32{Int32: courierID, Valid: true},
	})
	if err != nil {
		if err == sql.ErrNoRows {
			return db.Order{}, fmt.Errorf("order %d not found: %w", orderID, sql.ErrNoRows)
		}
		return db.Order{}, fmt.Errorf("AssignCourier: %w", err)
	}
	return order, nil
}

func (r *orderRepository) CancelOrder(ctx context.Context, id int32) (db.Order, error) {
	order, err := r.queries.CancelOrder(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return db.Order{}, fmt.Errorf("order %d not found: %w", id, sql.ErrNoRows)
		}
		return db.Order{}, fmt.Errorf("CancelOrder: %w", err)
	}
	return order, nil
}

func (r *orderRepository) GetAllCouriers(ctx context.Context) ([]db.Courier, error) {
	couriers, err := r.queries.GetAllCouriers(ctx)
	if err != nil {
		return nil, fmt.Errorf("GetAllCouriers: %w", err)
	}
	return couriers, nil
}

func (r *orderRepository) GetAvailableCouriers(ctx context.Context) ([]db.Courier, error) {
	couriers, err := r.queries.GetAvailableCouriers(ctx)
	if err != nil {
		return nil, fmt.Errorf("GetAvailableCouriers: %w", err)
	}
	return couriers, nil
}

func (r *orderRepository) GetCourierByID(ctx context.Context, id int32) (db.Courier, error) {
	courier, err := r.queries.GetCourierByID(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return db.Courier{}, fmt.Errorf("courier %d not found: %w", id, sql.ErrNoRows)
		}
		return db.Courier{}, fmt.Errorf("GetCourierByID: %w", err)
	}
	return courier, nil
}

func (r *orderRepository) UpdateCourierStatus(ctx context.Context, id int32, status string) (db.Courier, error) {
	courier, err := r.queries.UpdateCourierStatus(ctx, db.UpdateCourierStatusParams{
		ID:     id,
		Status: status,
	})
	if err != nil {
		if err == sql.ErrNoRows {
			return db.Courier{}, fmt.Errorf("courier %d not found: %w", id, sql.ErrNoRows)
		}
		return db.Courier{}, fmt.Errorf("UpdateCourierStatus: %w", err)
	}
	return courier, nil
}
