// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/menu_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/menu_service.go -destination=internal/services/mocks/menu_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "bar108/internal/db"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockmenuStore is a mock of menuStore interface.
type MockmenuStore struct {
	ctrl     *gomock.Controller
	recorder *MockmenuStoreMockRecorder
	isgomock struct{}
}

// MockmenuStoreMockRecorder is the mock recorder for MockmenuStore.
type MockmenuStoreMockRecorder struct {
	mock *MockmenuStore
}

// NewMockmenuStore creates a new mock instance.
func NewMockmenuStore(ctrl *gomock.Controller) *MockmenuStore {
	mock := &MockmenuStore{ctrl: ctrl}
	mock.recorder = &MockmenuStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmenuStore) EXPECT() *MockmenuStoreMockRecorder {
	return m.recorder
}

// CreateMenuItem mocks base method.
func (m *MockmenuStore) CreateMenuItem(ctx context.Context, arg db.CreateMenuItemParams) (db.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMenuItem", ctx, arg)
	ret0, _ := ret[0].(db.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMenuItem indicates an expected call of CreateMenuItem.
func (mr *MockmenuStoreMockRecorder) CreateMenuItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenuItem", reflect.TypeOf((*MockmenuStore)(nil).CreateMenuItem), ctx, arg)
}

// DeleteMenuItem mocks base method.
func (m *MockmenuStore) DeleteMenuItem(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMenuItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMenuItem indicates an expected call of DeleteMenuItem.
func (mr *MockmenuStoreMockRecorder) DeleteMenuItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMenuItem", reflect.TypeOf((*MockmenuStore)(nil).DeleteMenuItem), ctx, id)
}

// GetAllCategories mocks base method.
func (m *MockmenuStore) GetAllCategories(ctx context.Context) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockmenuStoreMockRecorder) GetAllCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockmenuStore)(nil).GetAllCategories), ctx)
}

// GetAllMenuItems mocks base method.
func (m *MockmenuStore) GetAllMenuItems(ctx context.Context) ([]db.GetAllMenuItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMenuItems", ctx)
	ret0, _ := ret[0].([]db.GetAllMenuItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMenuItems indicates an expected call of GetAllMenuItems.
func (mr *MockmenuStoreMockRecorder) GetAllMenuItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMenuItems", reflect.TypeOf((*MockmenuStore)(nil).GetAllMenuItems), ctx)
}

// GetMenuItemByID mocks base method.
func (m *MockmenuStore) GetMenuItemByID(ctx context.Context, id int32) (db.GetMenuItemByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuItemByID", ctx, id)
	ret0, _ := ret[0].(db.GetMenuItemByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuItemByID indicates an expected call of GetMenuItemByID.
func (mr *MockmenuStoreMockRecorder) GetMenuItemByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuItemByID", reflect.TypeOf((*MockmenuStore)(nil).GetMenuItemByID), ctx, id)
}

// UpdateMenuItem mocks base method.
func (m *MockmenuStore) UpdateMenuItem(ctx context.Context, arg db.UpdateMenuItemParams) (db.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenuItem", ctx, arg)
	ret0, _ := ret[0].(db.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMenuItem indicates an expected call of UpdateMenuItem.
func (mr *MockmenuStoreMockRecorder) UpdateMenuItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenuItem", reflect.TypeOf((*MockmenuStore)(nil).UpdateMenuItem), ctx, arg)
}

// MockMenuService is a mock of MenuService interface.
type MockMenuService struct {
	ctrl     *gomock.Controller
	recorder *MockMenuServiceMockRecorder
	isgomock struct{}
}

// MockMenuServiceMockRecorder is the mock recorder for MockMenuService.
type MockMenuServiceMockRecorder struct {
	mock *MockMenuService
}

// NewMockMenuService creates a new mock instance.
func NewMockMenuService(ctrl *gomock.Controller) *MockMenuService {
	mock := &MockMenuService{ctrl: ctrl}
	mock.recorder = &MockMenuServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuService) EXPECT() *MockMenuServiceMockRecorder {
	return m.recorder
}

// CreateMenuItem mocks base method.
func (m *MockMenuService) CreateMenuItem(ctx context.Context, arg db.CreateMenuItemParams) (db.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMenuItem", ctx, arg)
	ret0, _ := ret[0].(db.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMenuItem indicates an expected call of CreateMenuItem.
func (mr *MockMenuServiceMockRecorder) CreateMenuItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenuItem", reflect.TypeOf((*MockMenuService)(nil).CreateMenuItem), ctx, arg)
}

// DeleteMenuItem mocks base method.
func (m *MockMenuService) DeleteMenuItem(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMenuItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMenuItem indicates an expected call of DeleteMenuItem.
func (mr *MockMenuServiceMockRecorder) DeleteMenuItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMenuItem", reflect.TypeOf((*MockMenuService)(nil).DeleteMenuItem), ctx, id)
}

// GetAllCategories mocks base method.
func (m *MockMenuService) GetAllCategories(ctx context.Context) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockMenuServiceMockRecorder) GetAllCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockMenuService)(nil).GetAllCategories), ctx)
}

// GetAllMenuItems mocks base method.
func (m *MockMenuService) GetAllMenuItems(ctx context.Context) ([]db.GetAllMenuItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMenuItems", ctx)
	ret0, _ := ret[0].([]db.GetAllMenuItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMenuItems indicates an expected call of GetAllMenuItems.
func (mr *MockMenuServiceMockRecorder) GetAllMenuItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMenuItems", reflect.TypeOf((*MockMenuService)(nil).GetAllMenuItems), ctx)
}

// GetMenuItemByID mocks base method.
func (m *MockMenuService) GetMenuItemByID(ctx context.Context, id int32) (db.GetMenuItemByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuItemByID", ctx, id)
	ret0, _ := ret[0].(db.GetMenuItemByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuItemByID indicates an expected call of GetMenuItemByID.
func (mr *MockMenuServiceMockRecorder) GetMenuItemByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuItemByID", reflect.TypeOf((*MockMenuService)(nil).GetMenuItemByID), ctx, id)
}

// UpdateMenuItem mocks base method.
func (m *MockMenuService) UpdateMenuItem(ctx context.Context, arg db.UpdateMenuItemParams) (db.MenuItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenuItem", ctx, arg)
	ret0, _ := ret[0].(db.MenuItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMenuItem indicates an expected call of UpdateMenuItem.
func (mr *MockMenuServiceMockRecorder) UpdateMenuItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenuItem", reflect.TypeOf((*MockMenuService)(nil).UpdateMenuItem), ctx, arg)
}
