// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/order_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/order_service.go -destination=internal/services/mocks/order_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "bar108/internal/db"
	repository "bar108/internal/repository"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockorderStore is a mock of orderStore interface.
type MockorderStore struct {
	ctrl     *gomock.Controller
	recorder *MockorderStoreMockRecorder
	isgomock struct{}
}

// MockorderStoreMockRecorder is the mock recorder for MockorderStore.
type MockorderStoreMockRecorder struct {
	mock *MockorderStore
}

// NewMockorderStore creates a new mock instance.
func NewMockorderStore(ctrl *gomock.Controller) *MockorderStore {
	mock := &MockorderStore{ctrl: ctrl}
	mock.recorder = &MockorderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderStore) EXPECT() *MockorderStoreMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *MockorderStore) AssignCourier(ctx context.Context, orderID, courierID int32) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, orderID, courierID)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockorderStoreMockRecorder) AssignCourier(ctx, orderID, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockorderStore)(nil).AssignCourier), ctx, orderID, courierID)
}

// CancelOrder mocks base method.
func (m *MockorderStore) CancelOrder(ctx context.Context, id int32) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, id)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockorderStoreMockRecorder) CancelOrder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockorderStore)(nil).CancelOrder), ctx, id)
}

// GetAllCouriers mocks base method.
func (m *MockorderStore) GetAllCouriers(ctx context.Context) ([]db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockorderStoreMockRecorder) GetAllCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockorderStore)(nil).GetAllCouriers), ctx)
}

// GetAllOrders mocks base method.
func (m *MockorderStore) GetAllOrders(ctx context.Context) ([]db.GetAllOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", ctx)
	ret0, _ := ret[0].([]db.GetAllOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockorderStoreMockRecorder) GetAllOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockorderStore)(nil).GetAllOrders), ctx)
}

// GetAvailableCouriers mocks base method.
func (m *MockorderStore) GetAvailableCouriers(ctx context.Context) ([]db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableCouriers", ctx)
	ret0, _ := ret[0].([]db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableCouriers indicates an expected call of GetAvailableCouriers.
func (mr *MockorderStoreMockRecorder) GetAvailableCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableCouriers", reflect.TypeOf((*MockorderStore)(nil).GetAvailableCouriers), ctx)
}

// GetCourierByID mocks base method.
func (m *MockorderStore) GetCourierByID(ctx context.Context, id int32) (db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierByID", ctx, id)
	ret0, _ := ret[0].(db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierByID indicates an expected call of GetCourierByID.
func (mr *MockorderStoreMockRecorder) GetCourierByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierByID", reflect.TypeOf((*MockorderStore)(nil).GetCourierByID), ctx, id)
}

// GetOrderByID mocks base method.
func (m *MockorderStore) GetOrderByID(ctx context.Context, id int32) (db.GetOrderByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(db.GetOrderByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockorderStoreMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockorderStore)(nil).GetOrderByID), ctx, id)
}

// GetOrderItems mocks base method.
func (m *MockorderStore) GetOrderItems(ctx context.Context, orderID int32) ([]db.GetOrderItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItems", ctx, orderID)
	ret0, _ := ret[0].([]db.GetOrderItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItems indicates an expected call of GetOrderItems.
func (mr *MockorderStoreMockRecorder) GetOrderItems(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItems", reflect.TypeOf((*MockorderStore)(nil).GetOrderItems), ctx, orderID)
}

// GetOrderStatusHistory mocks base method.
func (m *MockorderStore) GetOrderStatusHistory(ctx context.Context, orderID int32) ([]db.OrderStatusHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatusHistory", ctx, orderID)
	ret0, _ := ret[0].([]db.OrderStatusHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatusHistory indicates an expected call of GetOrderStatusHistory.
func (mr *MockorderStoreMockRecorder) GetOrderStatusHistory(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatusHistory", reflect.TypeOf((*MockorderStore)(nil).GetOrderStatusHistory), ctx, orderID)
}

// GetOrdersByUserID mocks base method.
func (m *MockorderStore) GetOrdersByUserID(ctx context.Context, userID int32) ([]db.GetOrdersByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]db.GetOrdersByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockorderStoreMockRecorder) GetOrdersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockorderStore)(nil).GetOrdersByUserID), ctx, userID)
}

// GetPendingOrders mocks base method.
func (m *MockorderStore) GetPendingOrders(ctx context.Context) ([]db.GetPendingOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOrders", ctx)
	ret0, _ := ret[0].([]db.GetPendingOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOrders indicates an expected call of GetPendingOrders.
func (mr *MockorderStoreMockRecorder) GetPendingOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOrders", reflect.TypeOf((*MockorderStore)(nil).GetPendingOrders), ctx)
}

// PlaceOrder mocks base method.
func (m *MockorderStore) PlaceOrder(ctx context.Context, input repository.PlaceOrderInput) (repository.PlaceOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceOrder", ctx, input)
	ret0, _ := ret[0].(repository.PlaceOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceOrder indicates an expected call of PlaceOrder.
func (mr *MockorderStoreMockRecorder) PlaceOrder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceOrder", reflect.TypeOf((*MockorderStore)(nil).PlaceOrder), ctx, input)
}

// UpdateCourierStatus mocks base method.
func (m *MockorderStore) UpdateCourierStatus(ctx context.Context, id int32, status string) (db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourierStatus", ctx, id, status)
	ret0, _ := ret[0].(db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCourierStatus indicates an expected call of UpdateCourierStatus.
func (mr *MockorderStoreMockRecorder) UpdateCourierStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourierStatus", reflect.TypeOf((*MockorderStore)(nil).UpdateCourierStatus), ctx, id, status)
}

// UpdateOrderStatus mocks base method.
func (m *MockorderStore) UpdateOrderStatus(ctx context.Context, id int32, status string) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, id, status)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockorderStoreMockRecorder) UpdateOrderStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockorderStore)(nil).UpdateOrderStatus), ctx, id, status)
}

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *MockOrderService) AssignCourier(ctx context.Context, orderID, courierID int32) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, orderID, courierID)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockOrderServiceMockRecorder) AssignCourier(ctx, orderID, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockOrderService)(nil).AssignCourier), ctx, orderID, courierID)
}

// CancelOrder mocks base method.
func (m *MockOrderService) CancelOrder(ctx context.Context, orderID int32) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderServiceMockRecorder) CancelOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderService)(nil).CancelOrder), ctx, orderID)
}

// GetAllCouriers mocks base method.
func (m *MockOrderService) GetAllCouriers(ctx context.Context) ([]db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCouriers", ctx)
	ret0, _ := ret[0].([]db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCouriers indicates an expected call of GetAllCouriers.
func (mr *MockOrderServiceMockRecorder) GetAllCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCouriers", reflect.TypeOf((*MockOrderService)(nil).GetAllCouriers), ctx)
}

// GetAllOrders mocks base method.
func (m *MockOrderService) GetAllOrders(ctx context.Context) ([]db.GetAllOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", ctx)
	ret0, _ := ret[0].([]db.GetAllOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrderServiceMockRecorder) GetAllOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrderService)(nil).GetAllOrders), ctx)
}

// GetAvailableCouriers mocks base method.
func (m *MockOrderService) GetAvailableCouriers(ctx context.Context) ([]db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableCouriers", ctx)
	ret0, _ := ret[0].([]db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableCouriers indicates an expected call of GetAvailableCouriers.
func (mr *MockOrderServiceMockRecorder) GetAvailableCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableCouriers", reflect.TypeOf((*MockOrderService)(nil).GetAvailableCouriers), ctx)
}

// GetCourierByID mocks base method.
func (m *MockOrderService) GetCourierByID(ctx context.Context, id int32) (db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierByID", ctx, id)
	ret0, _ := ret[0].(db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierByID indicates an expected call of GetCourierByID.
func (mr *MockOrderServiceMockRecorder) GetCourierByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierByID", reflect.TypeOf((*MockOrderService)(nil).GetCourierByID), ctx, id)
}

// GetOrderByID mocks base method.
func (m *MockOrderService) GetOrderByID(ctx context.Context, id int32) (db.GetOrderByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(db.GetOrderByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderServiceMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderService)(nil).GetOrderByID), ctx, id)
}

// GetOrderItems mocks base method.
func (m *MockOrderService) GetOrderItems(ctx context.Context, orderID int32) ([]db.GetOrderItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItems", ctx, orderID)
	ret0, _ := ret[0].([]db.GetOrderItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItems indicates an expected call of GetOrderItems.
func (mr *MockOrderServiceMockRecorder) GetOrderItems(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItems", reflect.TypeOf((*MockOrderService)(nil).GetOrderItems), ctx, orderID)
}

// GetOrderStatusHistory mocks base method.
func (m *MockOrderService) GetOrderStatusHistory(ctx context.Context, orderID int32) ([]db.OrderStatusHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatusHistory", ctx, orderID)
	ret0, _ := ret[0].([]db.OrderStatusHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatusHistory indicates an expected call of GetOrderStatusHistory.
func (mr *MockOrderServiceMockRecorder) GetOrderStatusHistory(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatusHistory", reflect.TypeOf((*MockOrderService)(nil).GetOrderStatusHistory), ctx, orderID)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderService) GetOrdersByUserID(ctx context.Context, userID int32) ([]db.GetOrdersByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]db.GetOrdersByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderServiceMockRecorder) GetOrdersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderService)(nil).GetOrdersByUserID), ctx, userID)
}

// GetPendingOrders mocks base method.
func (m *MockOrderService) GetPendingOrders(ctx context.Context) ([]db.GetPendingOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOrders", ctx)
	ret0, _ := ret[0].([]db.GetPendingOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOrders indicates an expected call of GetPendingOrders.
func (mr *MockOrderServiceMockRecorder) GetPendingOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOrders", reflect.TypeOf((*MockOrderService)(nil).GetPendingOrders), ctx)
}

// PlaceOrder mocks base method.
func (m *MockOrderService) PlaceOrder(ctx context.Context, input repository.PlaceOrderInput) (repository.PlaceOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceOrder", ctx, input)
	ret0, _ := ret[0].(repository.PlaceOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceOrder indicates an expected call of PlaceOrder.
func (mr *MockOrderServiceMockRecorder) PlaceOrder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceOrder", reflect.TypeOf((*MockOrderService)(nil).PlaceOrder), ctx, input)
}

// UpdateCourierStatus mocks base method.
func (m *MockOrderService) UpdateCourierStatus(ctx context.Context, id int32, status string) (db.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourierStatus", ctx, id, status)
	ret0, _ := ret[0].(db.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCourierStatus indicates an expected call of UpdateCourierStatus.
func (mr *MockOrderServiceMockRecorder) UpdateCourierStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourierStatus", reflect.TypeOf((*MockOrderService)(nil).UpdateCourierStatus), ctx, id, status)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderService) UpdateOrderStatus(ctx context.Context, orderID int32, status string) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, status)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderServiceMockRecorder) UpdateOrderStatus(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderStatus), ctx, orderID, status)
}
