// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (
    category_id,
    name,
    description,
    price,
    available
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, category_id, name, description, price, available, created_at
`

type CreateMenuItemParams struct {
	CategoryID  int32          `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Available   bool           `json:"available"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, createMenuItem,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Available,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items
WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMenuItem, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, created_at
FROM categories
ORDER BY name ASC
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMenuItems = `-- name: GetAllMenuItems :many
SELECT 
    m.id,
    m.name,
    m.description,
    m.price,
    m.available,
    m.created_at,
    c.id AS category_id,
    c.name AS category_name
FROM menu_items m
JOIN categories c ON c.id = m.category_id
WHERE m.available = true
ORDER BY c.name, m.name
`

type GetAllMenuItemsRow struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Available    bool           `json:"available"`
	CreatedAt    time.Time      `json:"created_at"`
	CategoryID   int32          `json:"category_id"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetAllMenuItems(ctx context.Context) ([]GetAllMenuItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMenuItemsRow
	for rows.Next() {
		var i GetAllMenuItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Available,
			&i.CreatedAt,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT
    m.id,
    m.name,
    m.description,
    m.price,
    m.available,
    m.created_at,
    c.id   AS category_id,
    c.name AS category_name
FROM menu_items m
JOIN categories c ON c.id = m.category_id
WHERE m.id = $1
`

type GetMenuItemByIDRow struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Available    bool           `json:"available"`
	CreatedAt    time.Time      `json:"created_at"`
	CategoryID   int32          `json:"category_id"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetMenuItemByID(ctx context.Context, id int32) (GetMenuItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMenuItemByID, id)
	var i GetMenuItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
		&i.CategoryID,
		&i.CategoryName,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET
    category_id = $2,
    name        = $3,
    description = $4,
    price       = $5,
    available   = $6
WHERE id = $1
RETURNING id, category_id, name, description, price, available, created_at
`

type UpdateMenuItemParams struct {
	ID          int32          `json:"id"`
	CategoryID  int32          `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Available   bool           `json:"available"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, updateMenuItem,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Available,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}
