// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type BonusTransaction struct {
	ID      int32         `json:"id"`
	UserID  int32         `json:"user_id"`
	OrderID sql.NullInt32 `json:"order_id"`
	// earned or redeemed
	Type      string         `json:"type"`
	Points    int32          `json:"points"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt time.Time      `json:"created_at"`
}

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Courier struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
	// available, busy, offline
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type MenuItem struct {
	ID          int32          `json:"id"`
	CategoryID  int32          `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Available   bool           `json:"available"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Order struct {
	ID          int32         `json:"id"`
	UserID      int32         `json:"user_id"`
	CourierID   sql.NullInt32 `json:"courier_id"`
	PromotionID sql.NullInt32 `json:"promotion_id"`
	// pending, confirmed, preparing, ready, out_for_delivery, delivered, cancelled
	Status          string         `json:"status"`
	TotalPrice      string         `json:"total_price"`
	DiscountAmount  string         `json:"discount_amount"`
	FinalPrice      string         `json:"final_price"`
	Notes           sql.NullString `json:"notes"`
	DeliveryAddress sql.NullString `json:"delivery_address"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type OrderItem struct {
	ID         int32     `json:"id"`
	OrderID    int32     `json:"order_id"`
	MenuItemID int32     `json:"menu_item_id"`
	Quantity   int32     `json:"quantity"`
	UnitPrice  string    `json:"unit_price"`
	CreatedAt  time.Time `json:"created_at"`
}

type OrderStatusHistory struct {
	ID        int32          `json:"id"`
	OrderID   int32          `json:"order_id"`
	Status    string         `json:"status"`
	Note      sql.NullString `json:"note"`
	ChangedAt time.Time      `json:"changed_at"`
}

type Promotion struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	// percentage or fixed
	DiscountType  string        `json:"discount_type"`
	DiscountValue string        `json:"discount_value"`
	UsageLimit    sql.NullInt32 `json:"usage_limit"`
	UsedCount     int32         `json:"used_count"`
	ExpiresAt     sql.NullTime  `json:"expires_at"`
	CreatedAt     time.Time     `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Phone        string    `json:"phone"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	BonusPoints  int32     `json:"bonus_points"`
	CreatedAt    time.Time `json:"created_at"`
	IsActive     bool      `json:"is_active"`
}
