// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const assignCourier = `-- name: AssignCourier :one
UPDATE orders
SET
    courier_id = $2,
    status     = 'out_for_delivery',
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, courier_id, promotion_id, status, total_price, discount_amount, final_price, notes, delivery_address, created_at, updated_at
`

type AssignCourierParams struct {
	ID        int32         `json:"id"`
	CourierID sql.NullInt32 `json:"courier_id"`
}

// Assigns a courier to an order.
// This also updates status to 'out_for_delivery' automatically
// because you only assign a courier when the order is ready to go.
func (q *Queries) AssignCourier(ctx context.Context, arg AssignCourierParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, assignCourier, arg.ID, arg.CourierID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourierID,
		&i.PromotionID,
		&i.Status,
		&i.TotalPrice,
		&i.DiscountAmount,
		&i.FinalPrice,
		&i.Notes,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET
    status     = 'cancelled',
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, courier_id, promotion_id, status, total_price, discount_amount, final_price, notes, delivery_address, created_at, updated_at
`

func (q *Queries) CancelOrder(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRowContext(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourierID,
		&i.PromotionID,
		&i.Status,
		&i.TotalPrice,
		&i.DiscountAmount,
		&i.FinalPrice,
		&i.Notes,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
    user_id,
    promotion_id,
    status,
    total_price,
    discount_amount,
    final_price,
    notes,
    delivery_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, courier_id, promotion_id, status, total_price, discount_amount, final_price, notes, delivery_address, created_at, updated_at
`

type CreateOrderParams struct {
	UserID          int32          `json:"user_id"`
	PromotionID     sql.NullInt32  `json:"promotion_id"`
	Status          string         `json:"status"`
	TotalPrice      string         `json:"total_price"`
	DiscountAmount  string         `json:"discount_amount"`
	FinalPrice      string         `json:"final_price"`
	Notes           sql.NullString `json:"notes"`
	DeliveryAddress sql.NullString `json:"delivery_address"`
}

// ORDERS
// Creates the main order row.
// Returns the full order so we can use its ID immediately.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.PromotionID,
		arg.Status,
		arg.TotalPrice,
		arg.DiscountAmount,
		arg.FinalPrice,
		arg.Notes,
		arg.DeliveryAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourierID,
		&i.PromotionID,
		&i.Status,
		&i.TotalPrice,
		&i.DiscountAmount,
		&i.FinalPrice,
		&i.Notes,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one

INSERT INTO order_items (
    order_id,
    menu_item_id,
    quantity,
    unit_price
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, order_id, menu_item_id, quantity, unit_price, created_at
`

type CreateOrderItemParams struct {
	OrderID    int32  `json:"order_id"`
	MenuItemID int32  `json:"menu_item_id"`
	Quantity   int32  `json:"quantity"`
	UnitPrice  string `json:"unit_price"`
}

// ORDER ITEMS
// Inserts one item line into an order.
// unit_price is passed explicitly — it's a snapshot
// of the price at the time of ordering, NOT a live reference.
// This is critical: menu prices can change, but order history must not.
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :one

INSERT INTO order_status_history (
    order_id,
    status,
    note
) VALUES (
    $1, $2, $3
)
RETURNING id, order_id, status, note, changed_at
`

type CreateOrderStatusHistoryParams struct {
	OrderID int32          `json:"order_id"`
	Status  string         `json:"status"`
	Note    sql.NullString `json:"note"`
}

// ORDER STATUS HISTORY
// Called every time an order status changes.
// Builds the full timeline a customer sees when tracking their order.
func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, createOrderStatusHistory, arg.OrderID, arg.Status, arg.Note)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Note,
		&i.ChangedAt,
	)
	return i, err
}

const getAllCouriers = `-- name: GetAllCouriers :many

SELECT id, name, phone, status, created_at FROM couriers ORDER BY name
`

// COURIERS
func (q *Queries) GetAllCouriers(ctx context.Context) ([]Courier, error) {
	rows, err := q.db.QueryContext(ctx, getAllCouriers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Courier
	for rows.Next() {
		var i Courier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT
    o.id, o.user_id, o.courier_id, o.promotion_id, o.status, o.total_price, o.discount_amount, o.final_price, o.notes, o.delivery_address, o.created_at, o.updated_at,
    u.name  AS customer_name,
    u.phone AS customer_phone
FROM orders o
JOIN users u ON u.id = o.user_id
ORDER BY o.created_at DESC
`

type GetAllOrdersRow struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	CourierID       sql.NullInt32  `json:"courier_id"`
	PromotionID     sql.NullInt32  `json:"promotion_id"`
	Status          string         `json:"status"`
	TotalPrice      string         `json:"total_price"`
	DiscountAmount  string         `json:"discount_amount"`
	FinalPrice      string         `json:"final_price"`
	Notes           sql.NullString `json:"notes"`
	DeliveryAddress sql.NullString `json:"delivery_address"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
}

// Admin endpoint — all orders, newest first.
func (q *Queries) GetAllOrders(ctx context.Context) ([]GetAllOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrdersRow
	for rows.Next() {
		var i GetAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourierID,
			&i.PromotionID,
			&i.Status,
			&i.TotalPrice,
			&i.DiscountAmount,
			&i.FinalPrice,
			&i.Notes,
			&i.DeliveryAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableCouriers = `-- name: GetAvailableCouriers :many
SELECT id, name, phone, status, created_at FROM couriers
WHERE status = 'available'
ORDER BY name
`

// Only couriers with status = 'available' can be assigned.
func (q *Queries) GetAvailableCouriers(ctx context.Context) ([]Courier, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableCouriers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Courier
	for rows.Next() {
		var i Courier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourierByID = `-- name: GetCourierByID :one
SELECT id, name, phone, status, created_at FROM couriers WHERE id = $1
`

func (q *Queries) GetCourierByID(ctx context.Context, id int32) (Courier, error) {
	row := q.db.QueryRowContext(ctx, getCourierByID, id)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    o.id, o.user_id, o.courier_id, o.promotion_id, o.status, o.total_price, o.discount_amount, o.final_price, o.notes, o.delivery_address, o.created_at, o.updated_at,
    u.name  AS customer_name,
    u.phone AS customer_phone
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.id = $1
`

type GetOrderByIDRow struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	CourierID       sql.NullInt32  `json:"courier_id"`
	PromotionID     sql.NullInt32  `json:"promotion_id"`
	Status          string         `json:"status"`
	TotalPrice      string         `json:"total_price"`
	DiscountAmount  string         `json:"discount_amount"`
	FinalPrice      string         `json:"final_price"`
	Notes           sql.NullString `json:"notes"`
	DeliveryAddress sql.NullString `json:"delivery_address"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
}

// Fetches a single order with its user info joined.
// We join users so the handler can return customer name
// without a second query.
func (q *Queries) GetOrderByID(ctx context.Context, id int32) (GetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourierID,
		&i.PromotionID,
		&i.Status,
		&i.TotalPrice,
		&i.DiscountAmount,
		&i.FinalPrice,
		&i.Notes,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.CustomerPhone,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT
    oi.id, oi.order_id, oi.menu_item_id, oi.quantity, oi.unit_price, oi.created_at,
    mi.name AS item_name
FROM order_items oi
JOIN menu_items mi ON mi.id = oi.menu_item_id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID         int32     `json:"id"`
	OrderID    int32     `json:"order_id"`
	MenuItemID int32     `json:"menu_item_id"`
	Quantity   int32     `json:"quantity"`
	UnitPrice  string    `json:"unit_price"`
	CreatedAt  time.Time `json:"created_at"`
	ItemName   string    `json:"item_name"`
}

// All items for a given order, with menu item name joined.
// We join menu_items so we don't need a second query to get names.
func (q *Queries) GetOrderItems(ctx context.Context, orderID int32) ([]GetOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.ItemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderStatusHistory = `-- name: GetOrderStatusHistory :many
SELECT id, order_id, status, note, changed_at
FROM order_status_history
WHERE order_id = $1
ORDER BY changed_at ASC
`

// Full status timeline for an order, oldest first.
// This is what the customer sees: "Confirmed at 13:02, Preparing at 13:15..."
func (q *Queries) GetOrderStatusHistory(ctx context.Context, orderID int32) ([]OrderStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, getOrderStatusHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderStatusHistory
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.Note,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT
    o.id, o.user_id, o.courier_id, o.promotion_id, o.status, o.total_price, o.discount_amount, o.final_price, o.notes, o.delivery_address, o.created_at, o.updated_at,
    u.name  AS customer_name,
    u.phone AS customer_phone
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.user_id = $1
ORDER BY o.created_at DESC
`

type GetOrdersByUserIDRow struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	CourierID       sql.NullInt32  `json:"courier_id"`
	PromotionID     sql.NullInt32  `json:"promotion_id"`
	Status          string         `json:"status"`
	TotalPrice      string         `json:"total_price"`
	DiscountAmount  string         `json:"discount_amount"`
	FinalPrice      string         `json:"final_price"`
	Notes           sql.NullString `json:"notes"`
	DeliveryAddress sql.NullString `json:"delivery_address"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
}

// All orders for a specific user, newest first.
func (q *Queries) GetOrdersByUserID(ctx context.Context, userID int32) ([]GetOrdersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIDRow
	for rows.Next() {
		var i GetOrdersByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourierID,
			&i.PromotionID,
			&i.Status,
			&i.TotalPrice,
			&i.DiscountAmount,
			&i.FinalPrice,
			&i.Notes,
			&i.DeliveryAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOrders = `-- name: GetPendingOrders :many
SELECT
    o.id, o.user_id, o.courier_id, o.promotion_id, o.status, o.total_price, o.discount_amount, o.final_price, o.notes, o.delivery_address, o.created_at, o.updated_at,
    u.name  AS customer_name,
    u.phone AS customer_phone
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.status = 'pending'
ORDER BY o.created_at ASC
`

type GetPendingOrdersRow struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	CourierID       sql.NullInt32  `json:"courier_id"`
	PromotionID     sql.NullInt32  `json:"promotion_id"`
	Status          string         `json:"status"`
	TotalPrice      string         `json:"total_price"`
	DiscountAmount  string         `json:"discount_amount"`
	FinalPrice      string         `json:"final_price"`
	Notes           sql.NullString `json:"notes"`
	DeliveryAddress sql.NullString `json:"delivery_address"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
}

// Admin dashboard — only unprocessed orders.
func (q *Queries) GetPendingOrders(ctx context.Context) ([]GetPendingOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOrdersRow
	for rows.Next() {
		var i GetPendingOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourierID,
			&i.PromotionID,
			&i.Status,
			&i.TotalPrice,
			&i.DiscountAmount,
			&i.FinalPrice,
			&i.Notes,
			&i.DeliveryAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromotionByCode = `-- name: GetPromotionByCode :one

SELECT id, code, discount_type, discount_value, usage_limit, used_count, expires_at, created_at
FROM promotions
WHERE code = $1
`

// PROMOTIONS
// Looks up a promo code. Called before placing an order
// to validate and calculate the discount.
func (q *Queries) GetPromotionByCode(ctx context.Context, code string) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, getPromotionByCode, code)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.UsageLimit,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPromotionUsage = `-- name: IncrementPromotionUsage :one
UPDATE promotions
SET used_count = used_count + 1
WHERE id = $1
RETURNING id, code, discount_type, discount_value, usage_limit, used_count, expires_at, created_at
`

// Called after an order is placed with a promo code.
// Increments the used_count so we can track and enforce usage_limit.
func (q *Queries) IncrementPromotionUsage(ctx context.Context, id int32) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, incrementPromotionUsage, id)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.UsageLimit,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCourierStatus = `-- name: UpdateCourierStatus :one
UPDATE couriers
SET status = $2
WHERE id = $1
RETURNING id, name, phone, status, created_at
`

type UpdateCourierStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCourierStatus(ctx context.Context, arg UpdateCourierStatusParams) (Courier, error) {
	row := q.db.QueryRowContext(ctx, updateCourierStatus, arg.ID, arg.Status)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, courier_id, promotion_id, status, total_price, discount_amount, final_price, notes, delivery_address, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

// Changes the order status.
// updated_at is refreshed so we know when the last change was.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourierID,
		&i.PromotionID,
		&i.Status,
		&i.TotalPrice,
		&i.DiscountAmount,
		&i.FinalPrice,
		&i.Notes,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
