// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	DeleteMenuItem(ctx context.Context, id int32) error
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllMenuItems(ctx context.Context) ([]GetAllMenuItemsRow, error)
	GetMenuItemByID(ctx context.Context, id int32) (GetMenuItemByIDRow, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
}

var _ Querier = (*Queries)(nil)
