// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET is_active = true
WHERE id = $1
RETURNING id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
`

func (q *Queries) ActivateUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, activateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    phone,
    email,
    password_hash,
    bonus_points
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	BonusPoints  int32  `json:"bonus_points"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.BonusPoints,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = false
WHERE id = $1
RETURNING id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
`

func (q *Queries) DeactivateUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
FROM users
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) GetActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.BonusPoints,
			&i.CreatedAt,
			&i.IsActive,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
FROM users
ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.BonusPoints,
			&i.CreatedAt,
			&i.IsActive,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
SELECT id, email, password_hash, role, is_active
FROM users
WHERE email = $1
`

type GetUserByEmailForAuthRow struct {
	ID           int32  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (GetUserByEmailForAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForAuth, email)
	var i GetUserByEmailForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const hasActiveOrdersByUserID = `-- name: HasActiveOrdersByUserID :one
SELECT EXISTS (
    SELECT 1
    FROM orders
    WHERE user_id = $1
      AND status IN ('pending', 'confirmed', 'preparing', 'ready', 'out_for_delivery')
) AS has_active_orders
`

func (q *Queries) HasActiveOrdersByUserID(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveOrdersByUserID, userID)
	var has_active_orders bool
	err := row.Scan(&has_active_orders)
	return has_active_orders, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    phone = $3,
    email = $4,
    password_hash = $5,
    bonus_points = $6,
    is_active = $7
WHERE id = $1
RETURNING id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
`

type UpdateUserParams struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	BonusPoints  int32  `json:"bonus_points"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.BonusPoints,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const updateUserBonusPoints = `-- name: UpdateUserBonusPoints :one
UPDATE users
SET
    bonus_points = $2
WHERE id = $1
RETURNING id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
`

type UpdateUserBonusPointsParams struct {
	ID          int32 `json:"id"`
	BonusPoints int32 `json:"bonus_points"`
}

func (q *Queries) UpdateUserBonusPoints(ctx context.Context, arg UpdateUserBonusPointsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserBonusPoints, arg.ID, arg.BonusPoints)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, name, phone, email, password_hash, bonus_points, created_at, is_active, role
`

type UpdateUserRoleParams struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.BonusPoints,
		&i.CreatedAt,
		&i.IsActive,
		&i.Role,
	)
	return i, err
}
